version: 2.1

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run tests
          command: echo "hello world"

workflows:
  test_my_app:
    jobs:
      - build_and_test
