version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
          gcloud auth list

workflows:
  test_my_app:
    jobs:
      - deploy
