version: 2.1
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
          gcloud auth list
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - setup_remote_docker
      - run: |
          docker pull nginx:latest

workflows:
  test_my_app:
    jobs:
      - deploy
