version: 2.1

parameters:
  gcp-container-registry-url:
    description: The base path to our container image registry URL
    type: string
    default: "europe-docker.pkg.dev/chimbuc-playground"

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
          gcloud auth list
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - setup_remote_docker
      - run: |
          docker pull nginx:latest
          docket tag nginx:latest <<parameters.gcp-container-registry-url>>/docker/nginx:latest
          docker push <<parameters.gcp-container-registry-url>>/docker/nginx:latest

workflows:
  build_and_push_image:
    jobs:
      - build
