version: 2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $GCP_SERVICE_ACCOUNT_KEY | gcloud auth activate-service-account --key-file=-
          gcloud auth list
          gcloud auth configure-docker europe-docker.pkg.dev
      - setup_remote_docker
      - run: |
          docker build -t europe-docker.pkg.dev/chimbuc-playground/nginx/nginx:latest .
          docker images
          docker push europe-docker.pkg.dev/chimbuc-playground/nginx/nginx:latest

workflows:
  build_and_push_image:
    jobs:
      - build
